### ISSUE TITLE
一部テンプレートで、メニューが表示されない

### ISSUE THREAD

**Issue by suicaversa** [megumiteam/nginx-cache-controller#12]
一部テンプレートにて、メニューに管理画面へのリンクが表示されません。

http://themeforest.net/item/newspaper/5489609
このテンプレートの様に、テンプレートの設定メニューが管理メニューの上部に追加される場合、
恐らくメニューが被ってしまい、管理画面に本プラグインのリンクが表示されません。

nginx-champuru/includes/admin.class.phpの178行目、該当部分を以下のように変更したら、表示されました。
```PHP
    $hook = add_menu_page(
        "Nginx Cache",
        "Nginx Cache",
        "administrator",
        "nginx-champuru",
        array(&$this, "admin_panel"),
        $icon
    );
```

**Comment by hideokamoto** [comment]
We do not support Non GPL Themes.
